
theme = "gruvbox-dark"
icons = "awesome5"

[[block]]
block = "net"
device = "wlp3s0"
format = "{ssid} {signal_strength} {speed_down} {graph_down}"
interval = 5
hide_missing = true
hide_inactive = true

[[block]]
block = "net"
device = "enp0s31f6"
format = "{ip} {speed_down} {graph_down}"
interval = 5
hide_missing = true
hide_inactive = true

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon}{available}/{used}"

[[block]]
block = "memory"
#format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
#format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"
format_mem = "{mem_total}/{mem_total_used}"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{barchart}"

[[block]]
block = "load"
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
